// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://lsyozrucfqyrnwaehxyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxzeW96cnVjZnF5cm53YWVoeHlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MzM5NDUsImV4cCI6MjA3MzAwOTk0NX0.68TpFah-iNeWF4PsswaHf0sAm906qMo6F9KyZ7vokQs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);